nested = [["A","B","C","D"],["E","F","G","H"],["I","J","K","L"],["M","N","O","P"]]

print("---------------")
print(f"{nested[0][0]} |", end = " ")
print(f"{nested[0][1]} |", end = " ")
print(f"{nested[0][2]} |", end = " ")
print(f"{nested[0][3]} |", end = " ")
print()
print("---------------")
print(f"{nested[1][0]} |", end = " ")
print(f"{nested[1][1]} |", end = " ")
print(f"{nested[1][2]} |", end = " ")
print(f"{nested[1][3]} |", end = " ")
print()
print("---------------")
print(f"{nested[2][0]} |", end = " ")
print(f"{nested[2][1]} |", end = " ")
print(f"{nested[2][2]} |", end = " ")
print(f"{nested[2][3]} |", end = " ")
print()
print("---------------")
print(f"{nested[3][0]} |", end = " ")
print(f"{nested[3][1]} |", end = " ")
print(f"{nested[3][2]} |", end = " ")
print(f"{nested[3][3]} |", end = " ")
print()
print("---------------")